data:
    dataset: "LSUN"
    category: "bedroom"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 32

model:
    type: "simple"
    in_channels